Story4Django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('tugas.urls'))
]

tugas/urls.py
from django.urls import path
from . import views
from django.contrib import admin


app_name = 'tugas'

urlpatterns = [
    path('',views.home,name='index'),
    path('friends/', views.friends, name='friends'),
    path('admin/', admin.site.urls),


]

tugas/models.py
from django.db import models

# Create your models here.
class ClassYear(models.Model):
    Batches = [('Omega  (2016)', 'Omega  (2016)'), ('Tarung   (2017)', 'Tarung   (2017)'), ('Quanta (2018)', 'Quanta (2018)'), ('Maung   (2019)', 'Maung   (2019)'), ('Others', 'Others')]
    batchyogs = models.CharField(max_length=30,choices=Batches, default = 'Quanta(2018)')

    def __str__(self):
        return self.batchyogs

class Person(models.Model):
    name = models.CharField(max_length=30, primary_key=True)
    hobby = models.CharField(max_length=30)
    favorite_food = models.CharField(max_length=30)
    favorite_drink = models.CharField(max_length=30)
    year = models.ForeignKey(ClassYear, on_delete = models.CASCADE, default= "")

    def __str__(self):
        return self.name

tugas/forms.py
from django import forms
from .models import Person
##Create your forms here
class PersonForm(forms.ModelForm):
    class Meta:
        model = Person
        fields = ('name', 'hobby', 'favorite_food','favorite_drink','year')

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control fontfriends'}),
            'hobby': forms.TextInput(attrs={'class': 'form-control'}),
            'favorite_food': forms.TextInput(attrs={'class': 'form-control'}),
            'favorite_drink': forms.TextInput(attrs={'class': 'form-control'}),
            'year': forms.Select(attrs={'class': 'form-control'}),
        }

tugas/views.py
from django.shortcuts import render,redirect
from .models import Person, ClassYear
from .forms import PersonForm
# Create your views here.
def home(request):
    return render(request,'pages/index.html',{})

def friends(request):
    if request.method == "POST":
        form = PersonForm(request.POST)
        if form.is_valid():
            form.save()
            
    else:
        form = PersonForm()

    persons = Person.objects.all()
    classyear = ClassYear.objects.all()

    response = {'persons' : persons, 'classyear': classyear,'form':PersonForm}
    return render(request, 'pages/friends.html', response)

tugas/templates/pages/friends.html
{% extends 'pages/navbar.html' %}

{% block content %}
<br><br><br><br><br>

    <h1 class="mt-5 text-center" style="font-weight: 700">Be My Friend!</h1>
<div class="container">
  <form method="POST" class="post-form">
        {% csrf_token %}
        <label style="font-size:20px; font-weight: 600" for="{{ form.name.id_for_label }}">Name</label>
        {{ form.name }} <br>
        <label style="font-size:20px; font-weight: 600" for="{{ form.name.id_for_label }}">Hobby</label>
        {{ form.hobby }} <br>
        <label style="font-size:20px; font-weight: 600" for="{{ form.name.id_for_label }}">Favorite Food</label>
        {{ form.favorite_food }} <br>
        <label style="font-size:20px; font-weight: 600" for="{{ form.name.id_for_label }}">Favorite Drink</label>
        {{ form.favorite_drink }} <br>
        <label style="font-size:20px; font-weight: 600" for="{{ form.name.id_for_label }}">Year</label>
        {{ form.year }} <br>


        <button type="submit" class="save btn btn-default" style="background-color: #FFD500">Submit</button>
    </form>
    <br><br>
</div>
<h1 class = "text-center mt-5 mb-5" style="font-weight:700">My Friends!</h1>
<div class=" col-lg-12 col-md-12 col-sm-12">
<div class="row">
<table class="table">
  <thead style="font-size: 25px">
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Hobby</th>
      <th scope="col">Favorite Food</th>
      <th scope="col">Favorite Drink</th>
      <th scope="col">Year</th>
    </tr>
  </thead>
  <tbody style="font-size: 20px">
    {% for person in persons %}
    <tr>
      <td>{{ person.name }}</td>
      <td>{{ person.hobby}}</td>
      <td>{{ person.favorite_food}}</td>
      <td>{{ person.favorite_drink}}</td>
      <td>{{ person.year }}</td>
    </tr>
    {% endfor %}

  </tbody>
</table>
</div>
</div>
{% endblock %}

tugas/templates/pages/index.html
{% extends 'pages/navbar.html' %}
{% load static %}
{% block content %}
<!DOCTYPE html>

<body id="homepage">



  <header id="frontpage">
    <div class="fp-content">
      <div class="container">
        <h1 style="font-size: 10vh">HELLO!</h1>
        <p1 style="font-size: 2vh">I'm Akbar Novial, a 19 year old computer science student <br> who's trying to survive university</p1>
      </div>
    </div>
  </header>

  <section id="about">
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-6 col-md-6 col-sm-12">
          <h1 class="font-weight-bolder ml-5" style="font-size:74px"><strong>A Little Bit <br> About Myself</strong></h1>
          <div class="container-paragraph ml-5">
            <p1 class="text-justify" style="font-size: 24px">I’m a 19 year old computer science student at the University of Indonesia who is easygoing and always eager to learn new skills. <br> Some of my hobbies are playing basketball and video games.</p1>
          </div>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-12" style="background:url(static/assets/propiccrop.jpg); background-repeat: no-repeat; min-height: 100vh; background-size: cover; backgroun">
        </div>
      </div>
    </div>
  </section>


  <section class="edu">
    <div class="container-fluid mb-1" style="background-color: #fff; min-width: 99.2vw;width:100%">
      <div class="row">
        <div class="col-lg-4 col-md-6 col-sm-12 text-center  mt-5">
          <h3 style="font-weight: 600">Elementary School</h3>
          <img class="elemschool mb-4" src="{% static 'assets/school-solid.svg' %}"></img>
          <h5 style="font-weight: 600">SDI Al - Ikhlas <br>(2006 - 2012)</h5>
        </div>
        <div class="col-lg-4 col-md-6 col-sm-12 text-center mt-5">
          <h3 style="font-weight: 600">Middle School & High School</h3>
          <img class="middleschool mb-3" src="{% static 'assets/school.png' %}"></img>
          <h4 style="font-weight: 600">SMP & SMA <br> Al - Azhar 1 <br>
            (2012 - 2018)
          </h4>
        </div>
        <div class="col-lg-4 col-md-12 col-sm-12 text-center mt-5">
          <h3 style="font-weight: 600">University</h3>
          <img class="university mb-1" src="{% static 'assets/university.png' %}"></img>
          <h4 style="font-weight: 600">University of Indonesia<br>
            (2018 - present)
          </h4>
        </div>
      </div>
    </div>
  </section>

  <section class="skills">
    <div class="container-fluid mt-4" style="background-color:#d7d7d7; min-width: 99.2vw;width:100%">
      <div class="row">
        <div class="col-lg-12 col-md-12 col-small-12 text-center">
          <h1 class="mt-5" style="font-family: Montserrat; font-weight: 800">Proficient In</h1>
          <div class="col-lg-12 col-md-12 col-small-1 mt-5 mb-5">
            <img class="python" src="{% static 'assets/pythonlogo.png' %}" alt="Python Logo">
            <img class="java" src="{% static 'assets/javalogo.png' %}" alt="Java Logo">
            <img class="html5" src="{% static 'assets/HTML5_Logo_512.png' %}" alt="HTML5 Logo">
            <img class="css3" src="{% static 'assets/css3logo.png' %}" alt="CSS3 Logo" style="width:auto; height:19.5vh">

          </div>
        </div>
      </div>
    </div>
  </section>

  <section id="contact">
    <div class="container" style="min-height:91vh;height:100%;padding-right: 10%">
      <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 mt-5 pt-5">
          <h1 style="font-weight:800; font-size: 5rem; margin-bottom: 10rem">How to Contact Me</h1>
          <div class="container">
          <img src="{% static 'assets/mail.png' %}" style="width:3rem;height:auto"><p1 style="font-size: 24px; font-weight: bold"> akbarnovial7@gmail.com</p1> </img><br>
            <a href="https://www.facebook.com/akbar.novial"><img src="{% static 'assets/facebook.png' %}" style="width:3rem;height:auto"></a><p1 style="font-size: 24px; font-weight: bold"> Akbar Novial</p1> </img><br>
        <a href="https://www.instagram.com/akbarnovial/?hl=en"> <img src="{%static 'assets/instagram.png' %}" style="width:3rem;height:auto"></a> <p1 style="font-size: 24px; font-weight: bold"> @akbarnovial</p1> </img>
        </div>
        </div>
        <!-- <img src="images/undraw_message_sent_1030.svg" style="height:50vh;width:auto;position: absolute; bottom:0;right:0"> -->
      </div>
    </div>


  </section>


{% include 'pages/yogs.html' %}

{% endblock %}

tugas/templates/pages/navbar.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
  {% load static %}
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
  <link href="https://fonts.googleapis.com/css?family=Bebas+Neue&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,600,700,800&display=swap" rel="stylesheet">



</head>
  <body>
    <nav class="my-navbar navbar-dark navbar navbar-expand-lg   fixed-top id=" mainNav"">
    <div class="container-fluid">
      <a class="navbar-brand" href="#homepage">Akbar Novial</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'tugas:index' %}">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/#about">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/#contact">Contact</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'tugas:friends' %}">Friends</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
{% block content %}
{% endblock %}
<script src="/static/js/jquery.js"></script>
<script src="/static/js/popper.js"></script>
<script src="/static/js/bootstrap.min.js"></script>
  </body>
</html>

tugas/templates/pages/yogs.html
{% load static %}

{% block content %}
{% endblock %}
<footer>
  <h1 style="font-size: 20px"> Copyright Akbar Novial 2020</h1>
</footer>